version: "2"
services:
  ui:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - webappnetwork
  api:
    build: ./api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - webappnetwork
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
