export const DASHBOARD = {
	GET_DASHBOARD_DATA: "GET_DASHBOARD_DATA",
	GET_DASHBOARD_TASKS: "GET_DASHBOARD_TASKS",
	UPDATE_TASK: "UPDATE_TASK",
	DELETE_TASK: "DELETE_TASK",
	CREATE_TASK: "CREATE_TASK",
};
export const SESSION = {
	SEND_LOGIN_CREDENTIALS: "SEND_LOGIN_CREDENTIALS",
};
export const UI = {
	SHOW_LOADER: "SHOW_LOADER",
};
